server:
  port: ${APPLICATION_PORT}
  servlet:
    context-path: /api
    encoding:
      force: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4
  shutdown: graceful

spring:
  main:
    banner-mode: off
    lazy-initialization: true
    register-shutdown-hook: false
    cloud-platform: none
  application:
    name: fast-food-soat

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: master
      initialization-fail-timeout: -1
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 0

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          autocommit: false
        generate_statistics: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 25
          fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true

  jackson:
    serialization:
      indent_output: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

security:
  auth:
    token:
      expiration: ${AUTH_TOKEN_EXPIRATION}

mercadopago:
  token: ${MP_TOKEN}
  collectorId: ${COLLECTOR_ID}
  posId: ${POS_ID}
  baseUrl: ${MP_BASE_URL}


